### ISSUE TITLE
Please consider a new release

### ISSUE THREAD

**Issue by tueda** [editorconfig-checker/editorconfig-checker.python#10]
Thank you for making the nice tool. It seems that development in the main editorconfig-checker repository is still going on (now version 2.3.3), but the core version of the Python wrapper is 2.2.0. Moreover, there is no tag available for pre-commit because the pre-commit hook has been put after the last tag of 2.1.0 (as meant by [this comment](https://github.com/editorconfig-checker/editorconfig-checker.python/pull/7#issuecomment-731656913), I guess). (To make [`pre-commit autoupdate`](https://pre-commit.com/#updating-hooks-automatically) work, tags are needed on the default branch of the GitHub repository.)

For now, I am satisfied with the pre-commit hook for the Python wrapper (by explicitly specifying a commit hash for 2.2.0), so I am not in a hurry, but still it would be nice if one could use it more easily in future. Ideally, such new releases for wrapper tools may be automated and triggered by creating a new tag on the main editorconfig-checker repository (so, related to https://github.com/editorconfig-checker/editorconfig-checker/issues/150).

**Comment by mstruebing** [comment]
@mmicu

**Comment by mmicu** [comment]
Hi @tueda, thank you for your feedback. I will dedicate a couple of hours during the weekend to try to figure out a solution for this issue.

**Comment by mmicu** [comment]
- https://github.com/editorconfig-checker/editorconfig-checker.python/releases/tag/2.3.3
- https://pypi.org/project/editorconfig-checker/2.3.3

**Comment by tueda** [comment]
@mmicu Thank you!
