### ISSUE TITLE
Installation via pre-commit is failing

### ISSUE THREAD

**Issue by antonagestam** [editorconfig-checker/editorconfig-checker.python#25]
Hi,

I run CI on a schedule for one of my projects and noticed it started failing on installations of this hook since a few days back: https://github.com/antonagestam/immoney/actions/runs/4771852951/jobs/8484046129

I haven't been able to look closer yet, and possibly won't be for a few weeks, so thought I'd just report it as-is. I can come back with more details later if needed.

Relevant part of log:

```
Running setup.py clean for editorconfig-checker
    Failed to build editorconfig-checker
stderr:
      error: subprocess-exited-with-error
      
      × python setup.py bdist_wheel did not run successfully.
      │ exit code: 1
      ╰─> [6 lines of output]
          /home/runner/.cache/pre-commit/repodm9yyx3e/py_env-python3.11/lib/python3.11/site-packages/setuptools/config/setupcfg.py:516: SetuptoolsDeprecationWarning: The license_file parameter is deprecated, use license_files instead.
            warnings.warn(msg, warning_class)
          running bdist_wheel
          running build
          running fetch_binaries
          error: [Errno 17] File exists: 'build/temp.linux-x86_64-cpython-311'
          [end of output]
      
      note: This error originates from a subprocess, and is likely not a problem with pip.
      ERROR: Failed building wheel for editorconfig-checker
    ERROR: Could not build wheels for editorconfig-checker, which is required to install pyproject.toml-based projects
```

Pre-commit config: https://github.com/antonagestam/immoney/blob/29ca3021ecf1f5826bb1ce924e94bfd14ffd070a/.pre-commit-config.yaml#L13

**Comment by antonagestam** [comment]
After clearing Github Actions caches, the issue seems to have gone away. I'm guessing this was some cache backwards incompatibility introduced by pre-commit. Closing for now.

**Comment by mmicu** [comment]
Sure. Thanks for the clear issue explanation as well as the solution.

**Comment by aiven-anton** [comment]
This seems to be happening again but for another project, this time versions of editorconfig-checker hasn't changed recently, so it might be something fishy underneath: https://github.com/Aiven-Open/kio/actions/runs/6403546388/job/17382418113
