### ISSUE TITLE
Upgrade to v3.0.3

### ISSUE THREAD

**Issue by mjnowen** [editorconfig-checker/editorconfig-checker.python#31]
Hi,
Can you upgrade your wrapper to align with latest v3.0.3 release?
https://hub.docker.com/r/mstruebing/editorconfig-checker/tags
Thanks.

**Comment by mmicu** [comment]
Hi. Sorry for my late reply. It should be done. Could you please check and let me know?

**Comment by echoix** [comment]
Is there an automated way to ensure that it is not forgotten in the future?

**Comment by mjnowen** [comment]
> Hi. Sorry for my late reply. It should be done. Could you please check and let me know?

Confirmed. All working well. Thanks!

**Comment by mmicu** [comment]
> Is there an automated way to ensure that it is not forgotten in the future?

Probably, it is something that it can be automated with some scripts, but I cannot explore such option at the moment.

As of now, I have just enabled release notifications from the main project to reduce chances of missing them.
